---
title: 'Notebook PREP for Project 01'
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 4
    fig_caption: true
    number_sections: true
my-var: "monte"  # https://bookdown.org/yihui/rmarkdown/html-document.html
---

# Project 1: Measure

### Writeup

The purpose of the write up is to demonstrate that you can build a final work product based on your research questions.

#### SECRET practice

We will build a work product where the data stays in a SECRET or private format.  It should not be uploaded to GitHub.

#### Data cleansing

I have provided the data in a compiled format.  In the notebook `unit_02_confirmatory_data_analysis\nascent\2020-10-23_descriptive-statistics.Rmd`, I have provided some clues on how to cleanse the data.  That task is yours.

I consider changing all of the results to one unit system part of data cleansing.  You can choose "inches" (in) or "centimeters" (cm) for your analysis depending on your culture and comfort with a given system.  This means, all of the data needs to be converted.  Please recall the `distance` work we have done, there is a library `measurements` and a function `conv_unit`.

#### Data collapsing

Some people have data for a person's "left" and "right" side of the body.  I have prepared code for you to collapse that data so (we assume) each side of the body is equal.  This is one option.  You can choose to keep the overall data and address NA's (missing values) if your research question is tied to body symmetry.

In the notebook on correlation in week 6, the section `1.2.3.3 Measure` has some code on to "getOne" measurement from the left or right.  If one is NA, it returns the other.  If they both are available, it returns the mean.

#### Data creation

There may be a few data features you may want to create.  I have the "arm span" and information about the "armpits" which would enable you to compute the internal "chest width" (from armpit to armpit).  There may be other data you can create in a similar fashion.

#### Data proportions

It is very likely that for each measure row, you would want to create "scaled variables to that person's height", also known as a proportion.

Alternatively, you could scale everything to a person's head height.

Alternatively, you could review lots of different proportions.  I suggested at one point that the foot-size and the "upper arm" (elbow-pit to arm-pit) are the same size (some basic Pythagorean theorem could get you there or close).

There are lots of possibilities, all depends on your interests.  

- Some say the unit of length of a "one foot" that we now decompose into 12 inches was a function of the actual length of the King's foot in England, and would change when a new King was crowned.  

- Another measure of length, the "cubit" is derived from the Latin word for "elbow"

- Galileo Galilei, the famous Italian polymath, literally sold his body parts when he died (quite the entrepreneur).  He had extremely long fingers.  In the museum in Firenze, they have on display a few of the fingers recovered.  Yes, I have seen them <https://www.museogalileo.it/it/>.  Most people miss this museum because they are too busy admiring David's proportions at the nearby Academia Gallery <https://en.wikipedia.org/wiki/David_(Michelangelo)>.


#### Data selection

Which columns are you going to use in your analysis.  The "covariates" will be necessary to describe the sample procedure, but for your research question maybe you just use a few of those, or none of those.

The summary statistics on the sample "covariates" and on the overall data are dependent on which columns you want to research.  This depends, or is constrained by your research question.  For example, in the "Joireman paper" we did collect a lot of other data, and even showed them a variant of an exercise motivator (Nike Ad):

<http://www.mshaffer.com/arizona/videos/exercise/010.mp3>

<http://www.mshaffer.com/arizona/videos/exercise/101.mp4>

<http://www.mshaffer.com/arizona/videos/exercise/110.mp4>

<http://www.mshaffer.com/arizona/videos/exercise/111.mp4>


## Project Research Question

Have you formulated one primary research question and possibly 2-3 subquestions.  Or maybe 2-3 primary questions?

The project was initially intended to be an exploration of the original data (distances), the computed proportions (as a function of head height), and its relationship to correlations.  However, you now have some experience with basic clustering techniques, so you could try to use them as well.  I would say **focus** on the key research question and don't deviate too far afield into clustering techniques that you don't report on "exploratory findings" that inform your research question.

# Preparation for Final Writeup

Use this space to include and run code that gets your data and research question prepared.

Alternatively, you can use another notebook.  You will submit a final "ZIP" file that contains the supporting documents and the final "PDF" product.  I will build the template for the "PDF" product and help with the tasks new to you in that regard.

The data cleanup, the research question, and the analysis is up to you.

I will be supporting the process of turning the results and data you prepare into a "work product".
